services:
  sqlserver:
  
    image: mcr.microsoft.com/mssql/server:2022-latest

    container_name: ev-economics-sql

    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}

    ports:
      - "1433:1433"

    volumes:
      - sqlserver-data:/var/opt/mssql

volumes:
  sqlserver-data:     